@baseUrl = http://localhost:8080/app-jee8/resources/sample
@amangousseUrl = http://localhost:8080/app-jee8/resources/amangousse
###
GET {{baseUrl}}/titans
###
POST {{baseUrl}}/test
Content-Type: application/json

{
    "name": "test",
    "age": "0"
}
###
GET {{baseUrl}}/amangousse
###
POST {{baseUrl}}/amangousse
Content-Type: application/json

{
    "name": "test",
    "job": "test"
}
###
DELETE  {{baseUrl}}/amangousse/test



###
GET {{amangousseUrl}}
###
POST {{amangousseUrl}}
Content-Type: application/json

{
    "name": "test",
    "job": "test"
}
###
DELETE  {{amangousseUrl}}/test
###
PUT {{amangousseUrl}}
Content-Type: application/json

{
    "name": "test",
    "job": "coco"
}



###
POST {{userUrl}}/create
Content-Type: application/json

{
  "email": "test@e.ee",
  "name": "test",
  "password": "111"
}
###
PUT {{userUrl}}/updatePwd
Content-Type: application/json

{
  "email": "test@e.ee",
  "password": "222"
}
###
POST {{userUrl}}/login
Content-Type: application/json

{
  "email": "test@e.ee",
  "password": "222"
}
###
PUT {{userUrl}}/updatePwd
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0QGUuZWUiLCJpc3MiOiJodHRwOi8vZHJ5LXJlZnVnZS0zMTQyNS5oZXJva3VhcHAuY29tL3Jlc291cmNlcy91c2VyL2xvZ2luIiwiaWF0IjoxNjU0Njc0MTQyLCJqdGkiOiIxIiwicm9sZSI6InVzZXIiLCJleHAiOjE2NTQ2NzQyNjJ9.RHOXR6ugzoLJRTyomCEzSWkg14XUOY1b7mDDPsNlEQM
Content-Type: application/json

{
  "email": "test@e.ee",
  "password": "222"
}
### sans email
PUT {{userUrl}}/updatePwd
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0QGUuZWUiLCJpc3MiOiJodHRwOi8vZHJ5LXJlZnVnZS0zMTQyNS5oZXJva3VhcHAuY29tL3Jlc291cmNlcy91c2VyL2xvZ2luIiwiaWF0IjoxNjU0Njc0MTcwLCJqdGkiOiIxIiwicm9sZSI6InVzZXIiLCJleHAiOjE2NTQ2NzQyOTB9.2cd5BcEdufCVpMvAH8sS71Gi2fZFzZAELNw97lL6quw
Content-Type: application/json

{
  "password": "222"
}
###
GET {{userUrl}}/logout
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0QGUuZWUiLCJpc3MiOiJodHRwOi8vZHJ5LXJlZnVnZS0zMTQyNS5oZXJva3VhcHAuY29tL3Jlc291cmNlcy91c2VyL2xvZ2luIiwiaWF0IjoxNjU0Njc0MzczLCJqdGkiOiIxIiwicm9sZSI6InVzZXIiLCJleHAiOjE2NTQ2NzQ0OTN9.a8PZVkp3ebVOmzpdSBmoSZZWMv0RE_VwfchNPtoKeis
###
GET {{userUrl}}/login
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0QGUuZWUiLCJpc3MiOiJodHRwOi8vZHJ5LXJlZnVnZS0zMTQyNS5oZXJva3VhcHAuY29tL3Jlc291cmNlcy91c2VyL2xvZ2luIiwiaWF0IjoxNjU0NjczOTA0LCJqdGkiOiIxIiwicm9sZSI6InVzZXIiLCJleHAiOjE2NTQ2NzQwMjR9.4g3amPOHvSZe0NNWs0FSGFE8mZqHdJY5D8ObKIdPzqA

###
GET {{AFUrl}}/filter/zonegeo
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0QGUuZWUiLCJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjgwODAvcmVzb3VyY2VzL3VzZXIvbG9naW4iLCJpYXQiOjE2NTQ2NzExMjAsImp0aSI6IjEiLCJyb2xlIjoidXNlciIsImV4cCI6MTY1NDY3MTI0MH0.KY7yj7135OwHdYyHyOCMmESsqy6SWdpeLMcEJ04J0kw

###
POST {{AFUrl}}/create
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0QGUuZWUiLCJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjgwODAvYXBwLWplZTgvcmVzb3VyY2VzL3VzZXIvbG9naW4iLCJpYXQiOjE2NTM3NzIyMjAsImp0aSI6IjEiLCJyb2xlIjoidXNlciIsImV4cCI6MTY1Mzc3MjM0MH0.30zRe4rL9wWAH854_uBgIDm-4OjGi1DsdJ9PYCeIhJ8
Content-Type: application/json

{
  "nom": "test",
  "pays": "test",
  "zonegeo": "test"
}

###
PUT {{AFUrl}}/update
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0QGUuZWUiLCJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjgwODAvYXBwLWplZTgvcmVzb3VyY2VzL3VzZXIvbG9naW4iLCJpYXQiOjE2NTM3NzIyMjAsImp0aSI6IjEiLCJyb2xlIjoidXNlciIsImV4cCI6MTY1Mzc3MjM0MH0.30zRe4rL9wWAH854_uBgIDm-4OjGi1DsdJ9PYCeIhJ8
Content-Type: application/json

{
  "nom": "test",
  "zonegeo": "222"
}

###
DELETE  {{AFUrl}}/delete/11
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0QGUuZWUiLCJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjgwODAvYXBwLWplZTgvcmVzb3VyY2VzL3VzZXIvbG9naW4iLCJpYXQiOjE2NTM3NzIyMjAsImp0aSI6IjEiLCJyb2xlIjoidXNlciIsImV4cCI6MTY1Mzc3MjM0MH0.30zRe4rL9wWAH854_uBgIDm-4OjGi1DsdJ9PYCeIhJ8
