@baseUrl = http://localhost:8080/app-jee8/resources/sample
@amangousseUrl = http://localhost:8080/app-jee8/resources/amangousse
###
GET {{baseUrl}}/titans
###
POST {{baseUrl}}/test
Content-Type: application/json

{
    "name": "test",
    "age": "0"
}
###
GET {{baseUrl}}/amangousse
###
POST {{baseUrl}}/amangousse
Content-Type: application/json

{
    "name": "test",
    "job": "test"
}
###
DELETE  {{baseUrl}}/amangousse/test



###
GET {{amangousseUrl}}
###
POST {{amangousseUrl}}
Content-Type: application/json

{
    "name": "test",
    "job": "test"
}
###
DELETE  {{amangousseUrl}}/test
###
PUT {{amangousseUrl}}
Content-Type: application/json

{
    "name": "test",
    "job": "coco"
}



###
POST {{userUrl}}/create
Content-Type: application/json

{
  "email": "test@e.ee",
  "name": "test",
  "password": "111"
}
###
PUT {{userUrl}}/updatePwd
Content-Type: application/json

{
  "email": "test@e.ee",
  "password": "222"
}
###
POST {{userUrl}}/login
Content-Type: application/json

{
  "email": "test@e.ee",
  "password": "111"
}
###
PUT {{userUrl}}/updatePwd
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0QGUuZWUiLCJpc3MiOiJodHRwOi8vZHJ5LXJlZnVnZS0zMTQyNS5oZXJva3VhcHAuY29tL3Jlc291cmNlcy91c2VyL2xvZ2luIiwiaWF0IjoxNjU0Njc4ODMzLCJqdGkiOiIxIiwicm9sZSI6InVzZXIiLCJleHAiOjE2NTQ2Nzg5NTN9.rq2n3lXWgdwoysRGIkmqR6qHfa34y_avrMmXtKQ8o74
Content-Type: application/json

{
  "email": "test@e.ee",
  "password": "222"
}
### sans email
PUT {{userUrl}}/updatePwd
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0QGUuZWUiLCJpc3MiOiJodHRwOi8vZHJ5LXJlZnVnZS0zMTQyNS5oZXJva3VhcHAuY29tL3Jlc291cmNlcy91c2VyL2xvZ2luIiwiaWF0IjoxNjU0Njc4NjQ0LCJqdGkiOiIxIiwicm9sZSI6InVzZXIiLCJleHAiOjE2NTQ2Nzg3NjR9.wDQM45DWotIQ2xWqsNDT3sGG6UGSu261s24zDiJ7pwU
Content-Type: application/json

{
  "password": "222"
}
###
GET {{userUrl}}/logout
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0QGUuZWUiLCJpc3MiOiJodHRwOi8vZmFzdC1mYWxscy02MzEwNS5oZXJva3VhcHAuY29tL3Jlc291cmNlcy91c2VyL2xvZ2luIiwiaWF0IjoxNjU0Nzg1NDUzLCJqdGkiOiIxIiwicm9sZSI6InVzZXIiLCJleHAiOjE2NTQ3ODU1NzN9.TsMUtJT-PX0P9Fyh-6B9FWIhOA7gWwm92XDtONQFBxU
###
GET {{userUrl}}/login
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0QGUuZWUiLCJpc3MiOiJodHRwOi8vZmFzdC1mYWxscy02MzEwNS5oZXJva3VhcHAuY29tL3Jlc291cmNlcy91c2VyL2xvZ2luIiwiaWF0IjoxNjU0Nzg1NDUzLCJqdGkiOiIxIiwicm9sZSI6InVzZXIiLCJleHAiOjE2NTQ3ODU1NzN9.TsMUtJT-PX0P9Fyh-6B9FWIhOA7gWwm92XDtONQFBxU
###
GET {{AFUrl}}/filter/zonegeo
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0QGUuZWUiLCJpc3MiOiJodHRwOi8vZmFzdC1mYWxscy02MzEwNS5oZXJva3VhcHAuY29tL3Jlc291cmNlcy91c2VyL2xvZ2luIiwiaWF0IjoxNjU0Nzg1NDUzLCJqdGkiOiIxIiwicm9sZSI6InVzZXIiLCJleHAiOjE2NTQ3ODU1NzN9.TsMUtJT-PX0P9Fyh-6B9FWIhOA7gWwm92XDtONQFBxU
###
POST {{AFUrl}}/create
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0QGUuZWUiLCJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjgwODAvcmVzb3VyY2VzL3VzZXIvbG9naW4iLCJpYXQiOjE2NTQ2OTk5MjYsImp0aSI6IjEiLCJyb2xlIjoidXNlciIsImV4cCI6MTY1NDcwMDA0Nn0.3S5wOiJwFL4IVIZZ1HACnJ5OgqOCFVuOuk9EQgbEWWQ
Content-Type: application/json

{
  "nom": "test",
  "pays": "test",
  "zonegeo": "test"
}

###
PUT {{AFUrl}}/update
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0QGUuZWUiLCJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjgwODAvYXBwLWplZTgvcmVzb3VyY2VzL3VzZXIvbG9naW4iLCJpYXQiOjE2NTM3NzIyMjAsImp0aSI6IjEiLCJyb2xlIjoidXNlciIsImV4cCI6MTY1Mzc3MjM0MH0.30zRe4rL9wWAH854_uBgIDm-4OjGi1DsdJ9PYCeIhJ8
Content-Type: application/json

{
  "nom": "test",
  "zonegeo": "222"
}

###
DELETE  {{AFUrl}}/delete/11
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0QGUuZWUiLCJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjgwODAvYXBwLWplZTgvcmVzb3VyY2VzL3VzZXIvbG9naW4iLCJpYXQiOjE2NTM3NzIyMjAsImp0aSI6IjEiLCJyb2xlIjoidXNlciIsImV4cCI6MTY1Mzc3MjM0MH0.30zRe4rL9wWAH854_uBgIDm-4OjGi1DsdJ9PYCeIhJ8
